version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatapp
  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080
  node:
    image: node:9
    restart: always
  web:
    image: nginx
    volumes:
      - ./dev.template
    ports:
      - "8080:80"
    env_file:
      - ./.env
    environment:
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    
volumes:
  db_data:
    driver: local